"""empty message

Revision ID: 1082454748f9
Revises: f2ca22b4477a
Create Date: 2018-05-03 10:37:02.257075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1082454748f9'
down_revision = 'f2ca22b4477a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('camera', sa.String(length=50), nullable=True),
    sa.Column('lens', sa.String(length=50), nullable=True),
    sa.Column('focus', sa.String(length=50), nullable=True),
    sa.Column('shutter', sa.String(length=50), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('genre')
    # ### end Alembic commands ###
