"""empty message

Revision ID: 82dad5a281c5
Revises: 1082454748f9
Create Date: 2018-05-06 11:31:17.596949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82dad5a281c5'
down_revision = '1082454748f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_photo_timestamp'), 'photo', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_timestamp'), table_name='photo')
    op.drop_column('photo', 'timestamp')
    # ### end Alembic commands ###
