"""empty message

Revision ID: f2ca22b4477a
Revises: 4e5dcfd2748f
Create Date: 2018-05-03 10:21:34.255829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ca22b4477a'
down_revision = '4e5dcfd2748f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    op.drop_table('photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('event', sa.VARCHAR(length=100), nullable=True),
    sa.Column('image', sa.VARCHAR(length=255), nullable=False),
    sa.Column('genre_id', sa.INTEGER(), nullable=True),
    sa.Column('synopsis', sa.TEXT(), nullable=True),
    sa.Column('camera', sa.VARCHAR(length=100), nullable=True),
    sa.Column('lens', sa.VARCHAR(length=100), nullable=True),
    sa.Column('focus', sa.VARCHAR(length=100), nullable=True),
    sa.Column('shutter', sa.VARCHAR(length=100), nullable=True),
    sa.Column('iso', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
